
#FindAll
GET http://localhost:4000/api/v1/wilders
Content-Type: application/json

###

# FindById
GET http://localhost:4000/api/v1/wilders/62272bc272d3f1ca282bfc45
Content-Type: application/json

###

#Create
POST http://localhost:4000/api/v1/wilders
Content-Type: application/json

{
    "name": "Bobob2",
    "city": "Bobopolis",
    "skills": [{"title": "CSS", "votes": 5}]
}

###

#Update
PATCH http://localhost:4000/api/v1/wilders/62272bc272d3f1ca282bfc45
Content-Type: application/json

{
    "name": "TestBobTest"
}

###

#UpdateAll
PUT http://localhost:4000/api/v1/wilders/62272bc272d3f1ca282bfc45
Content-Type: application/json

{
    "name": "Test"
}

###

#Delete
DELETE http://localhost:4000/api/v1/wilders/62286cbf210b9a307e66bd63
Content-Type: application/json

###
